[package]
name = "s-code"
version = "0.1.0"
authors = ["Josh <jmw33@st-andrews.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"